src/components/ui/button.tsx
src/index.css
src/main.tsx

- Button 컴포넌트를 구현했습니다.
- 왼쪽부터 `PrimarySolid`, `SecondarySolid`, `PrimaryOutline`, `SecondaryOutline`, `Link` 입니다.
- 관련 디자인은 [피그마 참고](https://www.figma.com/design/w7l8x6CSHno2l5Wa6rOfs6/9%EC%A1%B0-%EA%B8%B0%ED%9A%8D-%ED%94%BC%EA%B7%B8%EB%A7%88?node-id=12041-10313&t=EFNOAv4NjM5mcDwq-4)

feat: Button 컴포넌트 구현

---

.gitignore
package-lock.json
package.json
src/App.tsx
src/app/MainPage.tsx
src/main.tsx
src/service/instance/defaultInstance.ts
src/service/instance/formInstance.ts

- API 연결을 하기 위한 사전 작업 진행
- `TanstackQuery`에서 제공하는 `QueryClientProvider`로 최상단 감싸기
- `axios instance` 구현 
- `App.tsx`가 최상위에 없었음
- 기존의 `App.tsx` -> `MainPage.tsx`로 수정
- 최상위에 `App.tsx` 만듦
- `main.tsx`는 DOM 관련 작업만 있으면 좋기 때문에 `Router`랑 `Header`, `NavBar` 전부 최상위 `App.tsx`로 옮김
- https://hihiha2.tistory.com/157
- https://velog.io/@rudans987/axios-%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4-%EC%82%AC%EC%9A%A9%EB%B2%95
- https://axios-http.com/kr/docs/instance

chore: api 연결 위한 설정

---

package-lock.json
package.json
src/app/detail/[postId]/DetailPostPage.tsx
src/assets/dummy-post-detail.ts
src/components/common/PostCard/PostContent.tsx
src/components/common/PostCard/PostFooter.tsx
src/components/common/PostCard/PostHeader.tsx
src/components/pages/PostDetail/ImageCarousel.tsx
src/components/pages/index.tsx
src/components/ui/carousel.tsx
src/types/PostDetailData.ts

- 게시글 상세보기 페이지의 UI를 구현했습니다.
- 게시글 상세보기 페이지에 필요한 `ImageCarousel` 구현
- PostFooter, PostContent, PostFooter 사용해서 상세보기 페이지 구현

feat: 게시글 상세보기 UI 구현

---

src/app/MainPage.tsx
src/components/pages/PostForm/CreatePostForm.tsx
src/components/pages/PostForm/ImageInput.tsx
src/hooks/mutations/usePostMutation.ts
src/hooks/queries/usePostListInfiniteQuery.ts
src/service/instance/formInstance.ts
src/service/post.ts
src/store/useCreatePostStore.ts

feat: 메인 페이지 게시글 기능 API 연결

---

src/components/pages/PostForm/CreatePostForm.tsx

fix: 빌드 에러 수정

---

src/app/detail/[postId]/DetailPostPage.tsx

fix: lint 에러 수정

---

src/api/queries/postQueries.ts
src/app/MainPage.tsx

- pageParam이 0으로만 요청된다는 오류 발견
- postQueries.list 안에서 pageParam을 조절하도록 수정

fix: infiniteQuery pageParam 오류 수정

---

.github/workflows/ci.yml
vite.config.ts

feat: Create FE CI

---

vite.config.ts

- `5173` 인데 `4173`으로 되어있던 port 번호 config 파일에서 수정

fix: port 번호 수정

---

package.json

packate.json에 unit test script가 빠져있어서 추가
아마 이전버전으로 push되서 안올라간듯함

Feat/fix package.json

---

src/api/instance/authInstance.ts
src/api/instance/defaultInstance.ts
src/api/instance/formInstance.ts
src/api/login.ts
src/api/post.ts
src/api/queries/postQueries.ts
src/app/MainPage.tsx
src/app/detail/[postId]/DetailPostPage.tsx
src/components/common/PostCard/PostCard.tsx
src/components/common/PostCard/PostContent.tsx
src/components/common/PostCard/PostFooter.tsx
src/components/pages/MemberForm/SignupForm.tsx
src/components/pages/PostForm/CreatePostForm.tsx

- 좋아요, 댓글, 공유하기 버튼 기능 연결
- 좋아요 버튼 눌렀을 때 like 요청 보냄
- 댓글 버튼 누르면 상세 페이지로 이동
- 공유하기 버튼 누르면 클립보드에 게시글 링크 복사되도록

feat: 게시글 부수 기능 연결

---

.github/workflows/ci.yml

push때 실행되는 조건 없앰
pull request 시에만 ci 실행으로 변경

delete push event

---

.github/workflows/ci.yml

modify ci code

---

.github/workflows/ci.yml

CD 조건 변경
unit test 필요 조건 제거
- 이슈 번호

modify CD condition

---

.github/workflows/ci.yml

cd스킵 조건 추가
skip cd 혹은 skip cd 를 commit 메시지에 포함시키면 cd 스킵
아직 ec2에서 docker image 기반 배포 준비가 되지 않아 그 전까지 cd 스킵 필요
- 이슈 번호

add skip cd condition

---

.github/workflows/ci.yml

add image push policy

---

src/api/instance/authInstance.ts
src/api/instance/formInstance.ts
src/api/login.ts
src/api/queries/loginQueries.ts
src/api/queries/postQueries.ts
src/app/MainPage.tsx
src/components/common/PostCard/PostFooter.tsx
src/components/pages/PostForm/CreatePostForm.tsx

Reverts 100-hours-a-week/9_meow_fe#87

Revert "fix: token으로 게시글 조회시 성능 최적화"

---

src/components/pages/PostForm/CreatePostForm.tsx
src/components/pages/PostForm/SelectEmotion.tsx

- 수정된 `ApiEmotion`과 `DisplayEmotion` 반영 안 된 곳 반영해줌
- 해당 없음

fix: build 에러 수정

---

.github/workflows/ci.yml

modify workflow code

---

.github/workflows/ci.yml

change ci code

---

.github/workflows/ci.yml

[skip ci] modify ci code

---

.github/workflows/ci.yml

debagging directory

---

.github/workflows/ci.yml

git secret에 vite api url 추가 후 docker build시 사용
- 이슈 번호

setting VITE_API_URL

---

index.html
src/App.tsx
src/app/create/CreatePostPage.tsx
src/app/detail/[postId]/DetailPostPage.tsx
src/components/common/Background.tsx
src/components/pages/Comment/CommentInput.tsx
src/index.css

- 댓글 기능 QA 과정에서 나온 오류들 수정함
1. 댓글 입력 완료하면 댓글 수도 업데이트 되도록 (그 전에는 댓글 불러오기만 새로되어서 댓글 count는 그대로였음)
2. 모바일 환경에서 스크롤 두개 되는 오류 수정
3. 모바일 환경에서 댓글 입력창 안 보이는 오류 수정
4. 모바일 환경에서 text 입력창 누르면 창이 확대되는 오류 수정
5. 모바일 환경에서 text 입력창 focus 시 파란색인 것 갈색으로 수정
- #121 
- local에서 띄운 내 앱을 모바일로 디버깅 하는 방법을 모름
- trent에게 물어봄 => `vite.config.ts` 에서 `server` 설정 & BE에서 CORS 설정
- `position: sticky`가 PC에선 잘 되는데 모바일에선 안됨
- #121 참고
- `position: fixed`로 어떤 환경에서도 잘 보이도록 수정
- `width: 80%; margin-x-auto` 설정도 추가
https://github.com/user-attachments/assets/db9455c9-4a7a-4984-a91e-7ff52b4de44a
- 모바일 환경에서 스크롤이 두개가 되어버림
https://github.com/user-attachments/assets/966de514-5a88-4f5c-8e09-655f300bd1cb
- 바깥쪽(`Header`와 `NavBar` 포함하는 `div`)에 `overflow:hidden`하고 그 안쪽 body 부분에 `overflow-y-auto` 설정
- 모바일 환경에서 입력창 클릭시 창이 확대되고, 테두리가 파란색 (PC에선 갈색) …

fix: 댓글 기능 오류 수정

---

src/api/image.ts
src/api/instance/s3Instance.ts
src/api/post.ts
src/api/queries/ImageQueries.ts
src/api/queries/postQueries.ts
src/api/types.ts
src/components/pages/PostForm/CreatePostForm.tsx
src/components/pages/PostForm/ImageInput.tsx
src/hooks/common/useImageUpload.ts

- FE에서 S3에 이미지를 업로드 하고, URL만 BE에 보낼 수 있도록 수정
- BE를 통해 presigned url을 받음 (POST)
- FE에서 presigned url에 이미지를 넣음 (PUT)
- BE에게 url만 전달 
- #134

feat: S3에 이미지 업로드 하는 기능 구현

---

src/App.tsx
src/api/post.ts
src/api/queries/loginQueries.ts
src/api/queries/postQueries.ts
src/api/types.ts
src/app/MainPage.tsx
src/app/detail/[postId]/DetailPostPage.tsx
src/app/edit/PostEdit.tsx
src/components/common/PostCard/ContextMenu.tsx
src/components/common/PostCard/PostHeader.tsx
src/components/pages/PostForm/EditPostForm.tsx
src/components/pages/PostForm/ImageInput.tsx
src/components/pages/PostForm/SelectEmotion.tsx
src/components/pages/index.tsx
src/hooks/common/useImageUpload.ts

- 게시글 수정/삭제 기능 구현
- 게시글 수정하기 버튼 클릭시 edit 페이지로 이동
- edit 이후 제출 버튼 누르면 edit API 요청 보내도록
- 게시글 삭제하기 버튼 클릭시 삭제 요청 보내도록
- 추가로, context menu에 z-index 추가 및 코드 리팩터링 진행
- #129

129/feat/게시글 수정 삭제 기능 연결

---

.github/workflows/ci.yml

CI코드에도 vite cloudfront url 변수 명시
- 이슈 번호

add vite cloudfront url to ci code

---

src/api/post.ts
src/api/queries/userQueries.ts
src/api/types/user.ts
src/api/user.ts
src/app/member/[userId]/follower/FollowerPage.tsx
src/app/member/[userId]/following/FollowingPage.tsx
src/components/pages/MemberPage/ProfileSummary.tsx
src/components/pages/MemberPage/ProfileSummary/ProfileInfo.tsx

- 팔로우/팔로잉 기능 구현
- 팔로우/언팔로우 기능 구현
- 팔로워/팔로잉 목록 조회
- #145

feat: 팔로우 팔로잉 기능 구현

---

src/components/common/PostCard/PostFooter.tsx

- 좋아요 누르면 모든 postQuery 무효화 되도록 함
- 이게 맞는건지는 고민이 필요할듯...
- #176

fix: 좋아요 성공시 게시글 쿼리 무효화

---

src/api/comment.ts
src/api/queries/ImageQueries.ts
src/api/queries/commentQueries.ts
src/api/queries/loginQueries.ts
src/api/queries/postQueries.ts
src/api/queries/signupQueries.ts
src/api/queries/userQueries.ts
src/api/utils/errorHandler.ts
src/app/create/CreatePostPage.tsx
src/app/login/LoginPage.tsx
src/app/redirect/RedirectPage.tsx
src/components/common/PostCard/PostFooter.tsx
src/components/pages/Comment/CommentInput.tsx
src/components/pages/Login/LoginButton.tsx
src/components/pages/MemberForm/EditProfileForm.tsx
src/components/pages/MemberForm/SignupForm.tsx
src/components/pages/MemberPage/ProfileSummary.tsx

fix: 로그인시 리다이렉트

---

src/api/queries/commentQueries.ts
src/api/queries/loginQueries.ts
src/api/queries/postQueries.ts
src/api/queries/signupQueries.ts
src/api/queries/userQueries.ts
src/components/pages/MemberForm/EditProfileForm.tsx
src/components/pages/MemberForm/SignupForm.tsx
src/hooks/common/useImageUpload.ts

- query option 관련 메서드 통일시킴
- 이슈 번호

refactor: query options 메서드 통일

---

.github/workflows/prod-CICD.yml

fix ci version tag

---

.github/workflows/prod-CICD.yml

add debug code

---

.github/workflows/prod-CICD.yml

fix prod_ci

---

.github/workflows/prod-CICD.yml

(cherry picked from commit 28481eec8fc5c2098ccaa44ad2e0421836d6d836)
- 이슈 번호

change user

---

.github/workflows/prod-CICD.yml

change file name

---

src/app/event/EventMainPage.tsx
src/app/event/[eventId]/EventDetailPage.tsx
src/app/event/submit/[eventId]/EventSubmitPage.tsx
src/app/event/vote/[eventId]/EventVotePage.tsx
src/components/common/UserItem.tsx
src/components/pages/Event/EventTop3.tsx
src/components/pages/Event/HistoryCard.tsx
src/components/pages/Event/ImageBox.tsx
src/components/pages/Event/PostCard.tsx
src/components/pages/Event/PostFooter.tsx
src/components/pages/Event/RecentPodium.tsx
src/components/pages/Event/Timer.tsx
src/index.css
src/utils/convertTimestamp.ts

- 팀 내 QA에서 나온 의견들 반영하여 UI 수정
- `Timer` 컴포넌트 가로 크기 꽉 차게
- 모바일 버전에서 이미지 잘리거나 넘어가지 않도록 반응형 추가
- `overscroll-none` 설정
- 신청 사진들 flex -> grid로 수정
- 카드들에 그림자 효과 추가
- 투표 기간에 프로필 화면으로 이동하지 않도록
- 발표 날짜 형식 수정 (00분 전 -> 0000년 00월 00일)
- #211

fix: 이벤트 기능 UI 수정

---

scripts/deploy_frontend.sh.tmpl

modify deploy sh

---

Dockerfile
nginx/nginx-prod.conf

(cherry picked from commit 7337db491d07553bdc69837502bc94391516c200)
- 이슈 번호

add nginx setting

---

.github/workflows/prod-CICD.yml

[skip cd] modify ci code

---

.github/workflows/prod-CICD.yml

[skip cd] fix version tag

---

src/app/chat/ChatPage.tsx
src/components/pages/Chat/ChatContainer.tsx
src/components/pages/Chat/ChatInput.tsx
src/components/pages/Chat/ChatMessage.tsx
src/components/pages/Chat/ChatUserItem.tsx
src/components/pages/MemberForm/SelectAnimalType.tsx
src/components/pages/index.tsx
src/types/animal.ts
src/utils/convertAnimal.ts

- 실시간 채팅을 위한 UI 구현
- `ChatUserItem` 컴포넌트
- `ChatMessage` 컴포넌트
- `ChatInput` 컴포넌트
- `ChatContainer` 컴포넌트
- `ChatPage` 구현
- 채팅에 활용되는 동물 종류 추가
- #231

231/feat/실시간 채팅 UI 구현

---

src/api/queries/userQueries.ts
src/api/types/user.ts
src/api/user.ts
src/api/utils/errorHandler.ts
src/components/pages/MemberForm/AISelectModal.tsx

- 프로필 이미지 추천 기능 API 수정됨
- 프로필 이미지 추천 기능의 요청/응답 API 수정되어서 코드 수정함
- API 실패시 alert 뜨도록 추가
- 없음

fix: 프로필 이미지 api 명세 수정

---

src/components/common/PostCard/ContextMenu.tsx
src/components/pages/PostForm/CreatePostForm.tsx
src/components/pages/PostForm/EditPostForm.tsx
src/types/Emotion.ts

- Context Menu 잘리는 오류 수정
- Context Menu가 아래 게시글에 의해 잘리는 경우 발생 => CreatePortal로 해결
- 감정 기본값 "선택 없음" -> "행복" 으로 수정
- 없음
> ContextMenu 잘림
> CreatePortal로 수정

fix: ContextMenu 잘리는 오류 수정

---

src/app/detail/[postId]/DetailPostPage.tsx
src/components/common/PostCard/PostCard.tsx
src/components/common/UserItem.tsx

- UI 일부 수정
- CAT/DOG 부분에 테두리 추가
- PostCard, CommentItem의 간격을 줄임
- 이슈 번호

style: UI 수정

---

src/api/queries/chatQueries.ts
src/api/types/chat.ts
src/app/chat/ChatPage.tsx
src/components/pages/Chat/ChatContainer.tsx
src/components/pages/Chat/ChatInput.tsx
src/hooks/common/useWebSocket.ts
src/utils/convertTimestamp.ts

- 실시간 채팅 추가 구현
- 기존에 간단하게 올려둔 실시간 채팅 고도화
- 메시지 전송 하고 나면 input 창 비워줌
- 시간 표시 `-1분전` 안나오도록
- 스크롤 최하단에 고정되고 상단으로 올릴수록 무한 스크롤 (상향식 무한 스크롤)
- 메시지 보내면 최 하단으로 스크롤되게
- #243 
> [[트러블슈팅] 상향식 무한 스크롤 대장정](https://velog.io/@coo1river/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-intersection-observer%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EB%AC%B4%ED%95%9C-%EC%8A%A4%ED%81%AC%EB%A1%A4)

feat: 실시간 채팅 기능 추가 구현
